# vim: syntax=yaml tabstop=2 expandtab
# coding: utf-8
#------------------------------------------------------------------------------
# Config file for somatic variant calling pipeline.
#------------------------------------------------------------------------------
# author   : Harald Detering
# email    : harald.detering@gmail.com
# modified : 2023-06-28
#------------------------------------------------------------------------------

ref-fasta-url: 'gs://gatk-legacy-bundles/b37/human_g1k_v37.fasta'
ref-dbsnp-url: 'gs://gatk-legacy-bundles/b37/dbsnp_138.b37.vcf'
ref-1000g-url: 'gs://gatk-legacy-bundles/b37/1000G_phase3_v4_20130502.sites.vcf'
ref-mills-url: 'gs://gatk-legacy-bundles/b37/Mills_and_1000G_gold_standard.indels.b37.vcf'
ref-fasta-path: 'temp/human_g1k_v37.fasta'
ref-dbsnp-path: 'temp/dbsnp_138.b37.vcf'
ref-1000g-path: 'temp/1000G_phase3_v4_20130502.sites.vcf'
ref-mills-path: 'temp/Mills_and_1000G_gold_standard.indels.b37.vcf'
ref-index-path: 'temp/human_g1k_v37.dict'

target-regions: '../data/target_regions.bed'
